# Generated by Django 5.2 on 2025-04-20 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('entry_requirements', models.TextField(blank=True)),
                ('vaccination_requirements', models.TextField(blank=True)),
                ('quarantine_requirements', models.TextField(blank=True)),
                ('documentation_timeline', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('general_requirements', models.TextField(blank=True)),
                ('airline_policies', models.TextField(blank=True)),
                ('carrier_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_queries', to='travel.country')),
                ('pet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pettype')),
                ('source_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_queries', to='travel.country')),
            ],
            options={
                'verbose_name_plural': 'User Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountryPetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_requirements', models.TextField()),
                ('additional_documents', models.TextField(blank=True)),
                ('prohibited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_requirements', to='travel.country')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_requirements', to='travel.pettype')),
            ],
            options={
                'ordering': ['country', 'pet_type'],
                'unique_together': {('country', 'pet_type')},
            },
        ),
    ]
