# Generated by Django 5.2 on 2025-04-20 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='userquery',
            name='feedback_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userquery',
            name='parent_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_queries', to='travel.userquery'),
        ),
        migrations.AddField(
            model_name='userquery',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='response_text',
            field=models.TextField(blank=True),
        ),
    ]
